export const laws_data = [
    {
        id: 1,
        title: "Free public Wi-Fi in all parks",
        category: "PUBLIC SERVICES",
        description: "Every park should be equipped with free and open Wi-Fi hotspots available to all visitors to promote accessibility, learning, and outdoor productivity.",
        upvotes: 2,
        downvotes: 1,
        comments: 2,
        createdAt: "2025-01-01 12:00",
    },
    {
        id: 2,
        title: "If a politician lies on air, they must apologize on air for 24 hours",
        category: "ACCOUNTABILITY",
        description: "Public figures who knowingly lie in broadcast media should be required to issue a full televised apology within 24 hours to maintain transparency and public trust.",
        upvotes: 3,
        downvotes: 2,
        comments: 3,
        createdAt: "2025-01-02 14:30",
    },
    {
        id: 3,
        title: "Every citizen should receive “no questions asked” day off once per month",
        category: "WORK",
        description: "All employees should be entitled to one unconditional paid day off each month to reduce burnout, improve mental health, and support work-life balance.",
        upvotes: 0,
        downvotes: 0,
        comments: 0,
        createdAt: "2025-01-03 09:15",
    },
    {
        id: 4,
        title: "Senders of unsolicited ads fined $100",
        category: "PRIVACY",
        description: "Individuals or companies that send unsolicited advertisements without user consent shall be penalized with a $100 fine per incident.",
        upvotes: 0,
        downvotes: 2,
        comments: 1,
        createdAt: "2025-01-04 11:45",
    },
    {
        id: 5,
        title: "Schools must include mental health education in their curriculum",
        category: "EDUCATION",
        description: "Mental health awareness and emotional intelligence should be core parts of school curricula to help students understand, cope with, and support psychological well-being.",
        upvotes: 1,
        downvotes: 1,
        comments: 0,
        createdAt: "2025-01-05 08:30",
    },
    {
        id: 6,
        title: "Ban single-use plastic bags in all grocery stores",
        category: "ENVIRONMENT",
        description: "To reduce plastic pollution, single-use plastic bags should be banned and replaced with reusable or biodegradable alternatives in all retail and grocery stores.",
        upvotes: 2,
        downvotes: 3,
        comments: 1,
        createdAt: "2025-01-06 10:10",
    },
    {
        id: 7,
        title: "Public transportation should be free during weekends",
        category: "TRANSPORTATION",
        description: "Free weekend transit will encourage greener travel, reduce traffic congestion, and make mobility more accessible to lower-income individuals and families.",
        upvotes: 2,
        downvotes: 0,
        comments: 0,
        createdAt: "2025-01-07 13:50",
    },
    {
        id: 8,
        title: "National Nap Hour should be introduced in all workplaces",
        category: "WELLNESS",
        description: "All workplaces should adopt a daily rest hour to allow employees to recharge, increasing overall happiness, productivity, and health.",
        upvotes: 0,
        downvotes: 1,
        comments: 1,
        createdAt: "2025-01-08 16:20",
    },
    {
        id: 9,
        title: "Require subtitles on all public TV broadcasts",
        category: "ACCESSIBILITY",
        description: "Subtitles should be mandatory on all public TV programs to ensure accessibility for the deaf and hard-of-hearing community.",
        upvotes: 0,
        downvotes: 0,
        comments: 0,
        createdAt: "2025-01-09 11:00",
    },
    {
        id: 10,
        title: "Government must publish all meeting minutes within 48 hours",
        category: "TRANSPARENCY",
        description: "All official governmental meetings should have publicly accessible minutes published within 48 hours to ensure accountability and informed citizenship.",
        upvotes: 2,
        downvotes: 1,
        comments: 1,
        createdAt: "2025-01-10 09:00",
    },
];


export const comments = [
    {
        id: 1,
        user: "EmilyWoods",
        avatar: "https://i.pravatar.cc/40?img=6",
        text: "Absolutely agree with this proposal! 🌿 Wi-Fi in parks will make them more accessible for everyone and encourage more community engagement.",
        time: "15 minutes ago",
    },
    {
        id: 2,
        user: "Holish23",
        avatar: "https://i.pravatar.cc/40?img=12",
        text: "Interesting idea, but who's going to cover the costs? I'd rather see budget go to maintenance.",
        time: "15 minutes ago",
    },
    {
        id: 3,
        user: "DataMage88",
        avatar: "https://i.pravatar.cc/40?img=8",
        text: "Public internet? Yes, but please secure it properly. Last thing we need is open networks for hackers.",
        time: "14 minutes ago",
    },
    {
        id: 4,
        user: "EcoLinda",
        avatar: "https://i.pravatar.cc/40?img=14",
        text: "Love it! 💚 Anything that gets people outdoors AND connected is a win for me.",
        time: "13 minutes ago",
    },
    {
        id: 5,
        user: "Skeptikron",
        avatar: "https://i.pravatar.cc/40?img=5",
        text: "Sounds nice, but what about areas with poor infrastructure already? Fix roads first maybe?",
        time: "12 minutes ago",
    },
    {
        id: 6,
        user: "SunnyDayz",
        avatar: "https://i.pravatar.cc/40?img=2",
        text: "Imagine working remotely from the park... dreamy! 🧑‍💻☀️",
        time: "12 minutes ago",
    },
    {
        id: 7,
        user: "NightCode",
        avatar: "https://i.pravatar.cc/40?img=9",
        text: "Free Wi-Fi could lead to more people camping out or loitering. Just saying.",
        time: "11 minutes ago",
    },
    {
        id: 8,
        user: "BetaVoter",
        avatar: "https://i.pravatar.cc/40?img=17",
        text: "Let’s try it in a few cities first before rolling it out nationwide. Pilot programs are key.",
        time: "11 minutes ago",
    },
    {
        id: 9,
        user: "AIEnthusiast",
        avatar: "https://i.pravatar.cc/40?img=7",
        text: "Why not integrate this with smart benches or solar-powered stations? Think future-forward. 🔋📶",
        time: "10 minutes ago",
    },
    {
        id: 10,
        user: "GreenTea42",
        avatar: "https://i.pravatar.cc/40?img=10",
        text: "This is a great equalizer for low-income families. They deserve digital access too.",
        time: "9 minutes ago",
    },
    {
        id: 11,
        user: "NoFilterNick",
        avatar: "https://i.pravatar.cc/40?img=3",
        text: "Public Wi-Fi always sounds better than it is. Slow speeds, lots of tracking, and spam.",
        time: "9 minutes ago",
    },
    {
        id: 12,
        user: "CivicKid",
        avatar: "https://i.pravatar.cc/40?img=4",
        text: "Simple, clear, and impactful. Just do it already.",
        time: "8 minutes ago",
    },
    {
        id: 13,
        user: "AnonymousOwl",
        avatar: "https://i.pravatar.cc/40?img=11",
        text: "What about content filtering? Kids will be online there too.",
        time: "8 minutes ago",
    },
    {
        id: 14,
        user: "GrumpyOldDev",
        avatar: "https://i.pravatar.cc/40?img=1",
        text: "In my day we went outside to escape the internet. 😤",
        time: "7 minutes ago",
    },
    {
        id: 15,
        user: "Visionary97",
        avatar: "https://i.pravatar.cc/40?img=18",
        text: "I think this is a stepping stone to fully connected smart cities. Let’s build forward.",
        time: "7 minutes ago",
    },
    {
        id: 16,
        user: "WiFiHunter",
        avatar: "https://i.pravatar.cc/40?img=13",
        text: "You had me at ‘free’.",
        time: "6 minutes ago",
    },
    {
        id: 17,
        user: "LibraryLover",
        avatar: "https://i.pravatar.cc/40?img=19",
        text: "As long as libraries don’t get budget cuts to fund this, I'm okay with it.",
        time: "6 minutes ago",
    },
    {
        id: 18,
        user: "ParkParent",
        avatar: "https://i.pravatar.cc/40?img=20",
        text: "Would love this while my kids are playing. Finally, a reason to stay at the playground longer.",
        time: "5 minutes ago",
    },
    {
        id: 19,
        user: "TrollTaco",
        avatar: "https://i.pravatar.cc/40?img=15",
        text: "Free Wi-Fi? Cool. Now I can lose ranked matches surrounded by squirrels.",
        time: "4 minutes ago",
    },
    {
        id: 20,
        user: "LegalNerd",
        avatar: "https://i.pravatar.cc/40?img=16",
        text: "Needs to include clear terms of use and data retention policies. Don’t overlook privacy laws!",
        time: "3 minutes ago",
    },
];
